spring.application.name=SpringSecEx

spring.security.user.name= dhruvil
spring.security.user.password=1234

spring.datasource.url=jdbc:mysql://localhost:3306/userSecurity
spring.datasource.username=root
spring.datasource.password=Dhruvil9094

